import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Open_Sans, Roboto_Mono } from 'next/font/google'; 
import Link from "next/link";
import { BiHome } from "react-icons/bi";
const Drawer = dynamic(() => import("../_layout/drawer"));
const Menu = dynamic(() => import("../_layout/menu"));
const Search = dynamic(() => import("../_layout/search"));
const ThemeHandler = dynamic(() => import("../_layout/themeHandler"));
const UserHandler = dynamic(() => import("../_layout/userHandler"));
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  //👇 Add variable to our object
  variable: '--font-opensans',
})
const robotoMono = Roboto_Mono({
  subsets: ['latin','cyrillic'],
  display: 'swap',
  variable: '--font-roboto-mono',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
export default function RootLayout({
  children,
  breadcrumb,
  gallery,title
}: {
  children: React.ReactNode;
  breadcrumb: React.ReactNode;
  gallery: React.ReactNode;title: React.ReactNode
}) {
  return (
    <> 
      <div
        className="col-start-1 col-end-[-1] row-end-[-2]  min-h-screen   rounded items-start  
                gap-x-2 gap-y-1 md:gap-y-4 md:p-2 lg:col-start-2 lg:dark:bg-slate-900 grid 
                auto-rows-min grid-cols-4" 
      >
        {breadcrumb}
        {title}
        {gallery}
        {children}
      </div>
      <header>
        <Link className="icon max-lg:!hidden" href="/">
          <BiHome />
        </Link>
        <Search />
        <Drawer>
          <Menu />
        </Drawer>
        <ThemeHandler />
        <UserHandler />
      </header>
      <aside  >
        <Menu />
      </aside>
      <footer className= {`${openSans.variable} ${robotoMono.variable} font-sans`}>
        <ul className="flex gap-8">
          <li>
            <Link href="/"> home</Link>
          </li>
          <li>
            <Link href="/item"> items</Link>
          </li>
          <li>
            <Link href="/item/first"> first</Link>
          </li>
          <li>
            <Link href="/articles">articles</Link>
          </li>
        </ul>
        <span className="block text-sm">© 2023. All Rights Reserved. </span>
      </footer>
    </>
  );
}
