import type { Metadata } from "next";
 
import dynamic from "next/dynamic";
import { Neucha } from "next/font/google";
import Link from "next/link";
import { BiHome } from "react-icons/bi";
const Drawer = dynamic(() => import("../_layout/drawer"));
const Menu = dynamic(() => import("../_layout/menu"));
const Search = dynamic(() => import("../_layout/search"));
const ThemeHandler = dynamic(() => import("../_layout/themeHandler"));
const UserHandler = dynamic(() => import("../_layout/userHandler"));
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const neucha = Neucha({
  subsets: ["latin", "cyrillic"],
  weight: "400",
});
export default function RootLayout({
  children,
  breadcrumb,
  gallery,
}: {
  children: React.ReactNode;
  breadcrumb: React.ReactNode;
  gallery: React.ReactNode;
}) {
  return (
    <>
      <div
        className="col-start-1 col-end-[-1] row-end-[-2] grid  grid-cols-1 min-h-screen 
        grid-rows-[2rem_min-content_1fr] child:col-start-1
                gap-x-2 gap-y-4  rounded p-2 lg:col-start-2 lg:dark:bg-slate-900"
      >
        {breadcrumb}
        {gallery}
        {children}
      </div>
      <header>
        <Link className="icon max-lg:!hidden" href="/">
          <BiHome />
        </Link>
        <Search />
        <Drawer>
          <Menu />
        </Drawer>
        <ThemeHandler />
        <UserHandler />
      </header>
      <aside  >
        <Menu />
      </aside>
      <footer className={neucha.className}>
        <ul className="flex gap-8">
          <li>
            <Link href="/"> home</Link>
          </li>
          <li>
            <Link href="/item"> items</Link>
          </li>
          <li>
            <Link href="/item/first"> first</Link>
          </li>
          <li>
            <Link href="/articles">articles</Link>
          </li>
        </ul>
        <span className="block text-sm">© 2023. All Rights Reserved. </span>
      </footer>
    </>
  );
}
