import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Roboto } from "next/font/google";
import Link from "next/link";
import { BiHome } from "react-icons/bi";
import { Neucha } from "next/font/google";
const Drawer = dynamic(() => import("../_components/drawer"));
const Menu = dynamic(() => import("../_components/menu"));
const Search = dynamic(() => import("../_components/search"));
const ThemeHandler = dynamic(() => import("../_components/themeHandler"));
const UserHandler = dynamic(() => import("../_components/userHandler"));
const roboto = Roboto({
  weight: "400",
  subsets: ["latin", "cyrillic"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app", 
};
const neucha = Neucha  ({
  subsets: ["latin", "cyrillic"],
  weight:"400"
}); 
export default function RootLayout({
  children,breadcrumb,gallery
}: {
    children: React.ReactNode ,
    breadcrumb: React.ReactNode,gallery: React.ReactNode
}) {
  return (
    <> 
      <div
        className="col-start-1 col-end-[-1] row-end-[-2] flex flex-col  
                rounded p-2  lg:col-start-2 lg:dark:bg-slate-900 gap-x-2 gap-y-4"
      >  
      
        {breadcrumb}
        {gallery} 
  {children} 
      </div>
      <header>
        <Link className="icon max-lg:!hidden" href="/">
          <BiHome />
        </Link>
        <Search />
        <Drawer>
          <Menu />
        </Drawer>
        <ThemeHandler />
        <UserHandler />
      </header>
      <aside className={roboto.className}>
        <Menu />
      </aside>
      <footer className={neucha.className}>
        <ul className="flex gap-8">
          <li>
            <Link href="/"> home</Link>
          </li>
          <li>
            <Link href="/content/items"> items</Link>
          </li>
          <li>
            <Link href="/content/items/first"> first</Link>
          </li>
          <li>
            <Link href="/content/articles">articles</Link>
          </li>
        </ul>
        <span className="block text-sm">© 2023. All Rights Reserved. </span>
      </footer>
    </>
  );
}
