import type { Metadata } from "next";

import { Inter, Roboto_Mono } from "next/font/google";
import Link from "next/link";
import NavBar from "./_layout/navBar";
import { mainMenu } from "./api/_data/menu";
import "./globals.css";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" className="dark">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        <NavBar />
        <div
          className="col-span-full col-start-2 row-start-2 grid h-full w-full grid-cols-6 
          grid-flow-row auto-rows-max max-lg:col-start-1  
         gap-y-4"
        >
          {children}
        </div>
        <aside>
          {mainMenu.map((l, i) => (
            <Link href={l[1]} key={i}>
              {l[0]}
            </Link>
          ))}
        </aside>
        <footer className={`font-sans`}>
          <ul className="flex gap-8">
            <li>
              <Link href="/"> home</Link>
            </li>
            <li>
              <Link href="/item"> items</Link>
            </li>
            <li>
              <Link href="/item/first"> first</Link>
            </li>
            <li>
              <Link href="/articles">articles</Link>
            </li>
          </ul>
          <span className="block text-sm">© 2023. All Rights Reserved. </span>
        </footer>
      </body>
    </html>
  );
}
