import type { Metadata } from "next";
import dynamic from 'next/dynamic';
import { Inter, Roboto } from "next/font/google";
import Link from "next/link";
import { BiHome } from "react-icons/bi";
import Drawer from "./components/drawer";
import Menu from "./components/menu";
import Search from "./components/search";
import "./globals.css";
 
const ThemeHandler = dynamic(() => import('./components/themeHandler') )

const roboto = Roboto({
  weight: "300",
  subsets: ["latin", "cyrillic"],
});
const inter = Inter({
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: {children: React.ReactNode;}) {
   
  return (
    <html lang="ru" className="dark">
      <body className={inter.className}> 
        <header> 
         <Drawer/>
          <Link className="hidden lg:block"
            href="/" 
          >
            <BiHome className="icon"/>
          </Link>  
        </header> 
        <ThemeHandler /> 
        <Search/>
        {children}  
        <aside className={roboto.className}>
         <Menu/>
        </aside> 
        <footer className={roboto.className}>
          <Link href="/" className="hover:text-slate-400 p-2">
            main
          </Link>
          footer
        </footer>
      </body>
    </html>
  );
}
