
import { Metadata } from "next";
import BackButton from "./backButton";

 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function Layout({ children,}: {children: React.ReactNode;}) {
  return <main className="z_mode center justify-center">
   <div className="bg1 rounded   grid grid-cols-1 gap-3 p-3 pt-0">
   {children} 
    <BackButton/>
    </div> </main> 
}
