
import BackButton from "@/app/components/elements/backButton";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function Layout({ children }: {children: React.ReactNode;}) {
  return <main className="z_mode center bg-slate-300">
   <div className="rounded-xl  border bg-slate-800 dark:bg-slate-800  border-slate-900  grid grid-cols-1 gap-3 p-3 pt-0">
   {children} 
    <BackButton/>
    </div> </main> 
}
